function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-Nov-2017 16:22:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),...
    'Color',[0.800000011920929 0.800000011920929 0.800000011920929]);

% Create xlabel
xlabel('time (s)');

% Create ylabel
ylabel('Extension (nm)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.5,'GridColor',...
    [0.247058823529412 0.247058823529412 0.247058823529412],'XColor',[0 0 0],...
    'XGrid','on','XTick',[0 0.5 1 1.5 2 2.5 3 3.5 4 4.5 5],'YColor',[0 0 0],...
    'YGrid','on','YTick',...
    [970 975 980 985 990 995 1000 1005 1010 1015 1020 1025 1030 1035 1040],...
    'ZColor',[0 0 0]);
